# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=255)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.BlogPost')),
            ],
        ),
    ]
